Repository jbesomi/texthero, pull requests merged in 2020-09, with the labels that each got.

#174 Fix type checks to not fail if first value in series is NaN/missing.
  .travis.yml
  setup.cfg
  tests/test_types.py
  texthero/_types.py
Labels: bug

#161 Added Pre commit hook
  .pre-commit-config.yaml
  CONTRIBUTING.md
  setup.cfg
Labels: testing

#185 Add and enforce best practices
  CONTRIBUTING.md
  texthero/preprocessing.py
  texthero/representation.py
  texthero/visualization.py
Labels: documentation

#186 Move stem from preprocessing to nlp
  tests/test_indexes.py
  texthero/nlp.py
  texthero/preprocessing.py
Labels: enhancement

#160 Unit-test/Travis CI: Cleaner Log, Features; Closes #137
  .travis.yml
  setup.cfg
  tests/test_nlp.py
  tests/test_representation.py
  texthero/_helper.py
  texthero/nlp.py
Labels: testing

#157 HeroTypes in Representation; DataFrame in _types
  tests/test_representation.py
  tests/test_types.py
  texthero/_types.py
  texthero/representation.py
  texthero/visualization.py
Labels: enhancement

#165 Fix Term_Frequency
  tests/test_representation.py
  texthero/representation.py
Labels: bug
